from __future__ import annotations

import ast
import difflib
import json
from dataclasses import dataclass, asdict
from pathlib import Path
from textwrap import indent

from .models import GeneratedArtifact, MutationResult, ProofReport


@dataclass
class GeneratedFixFile:
    path: str
    reason: str
    content: str


@dataclass
class FixBundle:
    generated_files: list[GeneratedFixFile]
    patch_path: str | None
    generated_tests_path: str | None
    summary_path: str | None
    applied: bool = False
    message: str = ""


def _safe_module_name(source_file: str) -> str:
    path = Path(source_file)
    if path.name == "__init__.py":
        return path.parent.as_posix().replace("/", ".")
    return path.with_suffix("").as_posix().replace("/", ".")


def _unique_generated_test_path(repo_path: Path, base: str = "tests/test_basalt_generated_proof.py") -> Path:
    path = repo_path / base
    if not path.exists():
        return path
    for i in range(2, 100):
        candidate = repo_path / f"tests/test_basalt_generated_proof_{i}.py"
        if not candidate.exists():
            return candidate
    return repo_path / "tests/test_basalt_generated_proof_latest.py"


def _value_literal(value: object) -> str:
    if isinstance(value, str):
        return repr(value)
    return repr(value)


def _find_python_boundary_candidate(source_text: str, mutation: MutationResult):
    """Return a small structured candidate for boundary-test generation.

    This deliberately handles the first MVP-safe case: simple functions whose
    behavior depends on a numeric boundary comparison, such as `age >= 18`.
    """
    try:
        tree = ast.parse(source_text)
    except SyntaxError:
        return None

    target_op = mutation.original
    op_names = {
        ast.GtE: "GtE",
        ast.Gt: "Gt",
        ast.LtE: "LtE",
        ast.Lt: "Lt",
        ast.Eq: "Eq",
        ast.NotEq: "NotEq",
    }

    for fn in [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]:
        if not fn.args.args:
            continue
        positional_args = [arg.arg for arg in fn.args.args]
        for node in ast.walk(fn):
            if not isinstance(node, ast.Compare) or not node.ops or not node.comparators:
                continue
            op = node.ops[0]
            op_name = next((name for cls, name in op_names.items() if isinstance(op, cls)), None)
            if op_name != target_op:
                continue

            left = node.left
            right = node.comparators[0]
            # MVP-safe form: variable OP numeric_constant, e.g. age >= 18.
            if isinstance(left, ast.Name) and isinstance(right, ast.Constant) and isinstance(right.value, (int, float)):
                if left.id not in positional_args:
                    continue
                if len(positional_args) != 1:
                    # Avoid guessing multi-parameter behavior for v1.1.
                    continue
                return {
                    "function": fn.name,
                    "arg": left.id,
                    "threshold": right.value,
                    "op": op_name,
                    "source_args": positional_args,
                }
    return None


def _assertions_for_boundary(candidate: dict) -> list[tuple[str, bool]]:
    threshold = candidate["threshold"]
    op = candidate["op"]
    one_less = threshold - 1 if isinstance(threshold, int) else threshold - 0.1
    one_more = threshold + 1 if isinstance(threshold, int) else threshold + 0.1

    if op == "GtE":
        return [(threshold, True), (one_less, False), (one_more, True)]
    if op == "Gt":
        return [(threshold, False), (one_more, True), (one_less, False)]
    if op == "LtE":
        return [(threshold, True), (one_more, False), (one_less, True)]
    if op == "Lt":
        return [(threshold, False), (one_less, True), (one_more, False)]
    return []


def _render_python_boundary_tests(module_name: str, candidate: dict, mutation: MutationResult) -> str:
    fn = candidate["function"]
    threshold = candidate["threshold"]
    tests = _assertions_for_boundary(candidate)
    lines: list[str] = [
        "import unittest",
        f"from {module_name} import {fn}",
        "",
        "",
        "class BasaltGeneratedProofTests(unittest.TestCase):",
        f"    \"\"\"Generated by Basalt to kill survived mutation: {mutation.original} -> {mutation.replacement}.\"\"\"",
    ]
    if tests:
        for value, expected in tests:
            label = str(value).replace("-", "negative_").replace(".", "_")
            lines.append("")
            lines.append(f"    def test_{fn}_boundary_{label}(self):")
            method = "assertTrue" if expected else "assertFalse"
            lines.append(f"        self.{method}({fn}({_value_literal(value)}))")
    else:
        lines.append("")
        lines.append(f"    def test_{fn}_mutation_guard(self):")
        lines.append(f"        # TODO: Add an assertion that fails when {mutation.original} changes to {mutation.replacement}.")
        lines.append(f"        self.fail('Basalt could not infer a safe boundary assertion for threshold {threshold!r}.')")
    lines.extend(["", "", "if __name__ == \"__main__\":", "    unittest.main()", ""])
    return "\n".join(lines)


def _find_python_binop_candidate(source_text: str, mutation: MutationResult):
    try:
        tree = ast.parse(source_text)
    except SyntaxError:
        return None
    if mutation.original not in {"Add", "Sub"}:
        return None
    for fn in [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]:
        positional_args = [arg.arg for arg in fn.args.args]
        if len(positional_args) != 2:
            continue
        for node in ast.walk(fn):
            if isinstance(node, ast.BinOp):
                op_name = type(node.op).__name__
                if op_name == mutation.original:
                    return {"function": fn.name, "args": positional_args, "op": op_name}
    return None


def _render_python_binop_tests(module_name: str, candidate: dict, mutation: MutationResult) -> str:
    fn = candidate["function"]
    if candidate["op"] == "Add":
        expected_one = 5
        expected_two = 0
    elif candidate["op"] == "Sub":
        expected_one = -1
        expected_two = -4
    else:
        expected_one = 5
        expected_two = 0
    return f'''import unittest
from {module_name} import {fn}


class BasaltGeneratedProofTests(unittest.TestCase):
    """Generated by Basalt to kill survived mutation: {mutation.original} -> {mutation.replacement}."""

    def test_{fn}_mutation_guard_positive_numbers(self):
        self.assertEqual({fn}(2, 3), {expected_one})

    def test_{fn}_mutation_guard_mixed_numbers(self):
        self.assertEqual({fn}(-2, 2), {expected_two})


if __name__ == "__main__":
    unittest.main()
'''




def _find_js_boundary_candidate(source_text: str, mutation: MutationResult):
    import re
    if mutation.original.strip() not in {">=", ">", "<=", "<"}:
        return None
    patterns = [
        re.compile(r"function\s+([A-Za-z_$][\w$]*)\s*\(\s*([A-Za-z_$][\w$]*)\s*\)\s*{\s*return\s+\2\s*(>=|>|<=|<)\s*(-?\d+(?:\.\d+)?)\s*;?\s*}"),
        re.compile(r"(?:const|let)\s+([A-Za-z_$][\w$]*)\s*=\s*\(?\s*([A-Za-z_$][\w$]*)\s*\)?\s*=>\s*\2\s*(>=|>|<=|<)\s*(-?\d+(?:\.\d+)?)"),
        re.compile(r"export\s+function\s+([A-Za-z_$][\w$]*)\s*\(\s*([A-Za-z_$][\w$]*)\s*\)\s*{\s*return\s+\2\s*(>=|>|<=|<)\s*(-?\d+(?:\.\d+)?)\s*;?\s*}"),
    ]
    for pattern in patterns:
        m = pattern.search(source_text)
        if not m:
            continue
        threshold_raw = m.group(4)
        threshold = int(threshold_raw) if threshold_raw.lstrip('-').isdigit() else float(threshold_raw)
        return {"function": m.group(1), "arg": m.group(2), "op": m.group(3), "threshold": threshold}
    return None


def _js_assertions(candidate: dict) -> list[tuple[object, bool]]:
    threshold = candidate["threshold"]
    op = candidate["op"]
    one_less = threshold - 1 if isinstance(threshold, int) else threshold - 0.1
    one_more = threshold + 1 if isinstance(threshold, int) else threshold + 0.1
    if op == ">=":
        return [(threshold, True), (one_less, False), (one_more, True)]
    if op == ">":
        return [(threshold, False), (one_more, True), (one_less, False)]
    if op == "<=":
        return [(threshold, True), (one_more, False), (one_less, True)]
    if op == "<":
        return [(threshold, False), (one_less, True), (one_more, False)]
    return []


def _unique_generated_js_test_path(repo_path: Path, base: str = "tests/basalt.generated.test.js") -> Path:
    path = repo_path / base
    if not path.exists():
        return path
    for i in range(2, 100):
        candidate = repo_path / f"tests/basalt.generated.test.{i}.js"
        if not candidate.exists():
            return candidate
    return repo_path / "tests/basalt.generated.test.latest.js"


def _render_js_boundary_tests(source_file: str, candidate: dict, mutation: MutationResult) -> str:
    source_path = Path(source_file)
    import_path = "../" + source_path.with_suffix("").as_posix()
    fn = candidate["function"]
    lines = [
        "const assert = require('assert');",
        f"const {{ {fn} }} = require('{import_path}');",
        "",
        f"// Generated by Basalt to kill survived mutation: {mutation.original} -> {mutation.replacement}.",
    ]
    for value, expected in _js_assertions(candidate):
        lines.append(f"assert.strictEqual({fn}({repr(value)}), {str(expected).lower()});")
    lines.append("console.log('Basalt generated proof-hardening tests passed.');")
    lines.append("")
    return "\n".join(lines)


def _generate_js_test_file(repo_path: Path, mutation: MutationResult) -> GeneratedFixFile | None:
    source = repo_path / mutation.file
    if source.suffix.lower() not in {".js", ".jsx", ".ts", ".tsx"} or not source.exists():
        return None
    source_text = source.read_text(encoding="utf-8", errors="ignore")
    candidate = _find_js_boundary_candidate(source_text, mutation)
    if not candidate:
        return None
    path = _unique_generated_js_test_path(repo_path)
    return GeneratedFixFile(
        path=str(path.relative_to(repo_path)),
        reason=f"Kills survived JS/TS boundary mutation in {mutation.file}: {mutation.original} -> {mutation.replacement}.",
        content=_render_js_boundary_tests(mutation.file, candidate, mutation),
    )


def _generate_python_test_file(repo_path: Path, mutation: MutationResult) -> GeneratedFixFile | None:
    source = repo_path / mutation.file
    if source.suffix != ".py" or not source.exists():
        return None
    source_text = source.read_text(encoding="utf-8", errors="ignore")
    module_name = _safe_module_name(mutation.file)

    candidate = _find_python_boundary_candidate(source_text, mutation)
    if candidate:
        test_content = _render_python_boundary_tests(module_name, candidate, mutation)
        path = _unique_generated_test_path(repo_path)
        return GeneratedFixFile(
            path=str(path.relative_to(repo_path)),
            reason=f"Kills survived boundary mutation in {mutation.file}: {mutation.original} -> {mutation.replacement}.",
            content=test_content,
        )

    binop_candidate = _find_python_binop_candidate(source_text, mutation)
    if binop_candidate:
        test_content = _render_python_binop_tests(module_name, binop_candidate, mutation)
        path = _unique_generated_test_path(repo_path)
        return GeneratedFixFile(
            path=str(path.relative_to(repo_path)),
            reason=f"Kills survived arithmetic mutation in {mutation.file}: {mutation.original} -> {mutation.replacement}.",
            content=test_content,
        )
    return None


def generate_fix_files(repo_path: Path, report: ProofReport) -> list[GeneratedFixFile]:
    files: list[GeneratedFixFile] = []
    seen_paths: set[str] = set()
    for mutation in report.mutations:
        if not mutation.survived:
            continue
        generated = _generate_python_test_file(repo_path, mutation) or _generate_js_test_file(repo_path, mutation)
        if generated and generated.path not in seen_paths:
            files.append(generated)
            seen_paths.add(generated.path)
    return files


def render_unified_patch(generated_files: list[GeneratedFixFile]) -> str:
    chunks: list[str] = []
    for file in generated_files:
        new_lines = file.content.splitlines()
        diff = difflib.unified_diff(
            [],
            new_lines,
            fromfile="/dev/null",
            tofile=f"b/{file.path}",
            lineterm="",
        )
        chunks.append("\n".join(diff))
    return "\n".join(chunks).rstrip() + ("\n" if chunks else "")


def render_generated_tests_markdown(report: ProofReport, generated_files: list[GeneratedFixFile]) -> str:
    lines = [
        "# Basalt Generated Fix Tests",
        "",
        f"Project: `{report.project_name}`",
        f"Source verdict: `{report.final_status.value}`",
        f"Source proof score: `{report.score}/100`",
        "",
        "Basalt generated these additive tests to convert weak proof into stronger proof. The MVP only adds tests; it does not rewrite production code.",
        "",
    ]
    if not generated_files:
        lines.append("No safe automatic test patch could be generated for this report.")
        return "\n".join(lines) + "\n"
    for file in generated_files:
        lines.append(f"## `{file.path}`")
        lines.append("")
        lines.append(f"Reason: {file.reason}")
        lines.append("")
        lines.append("```python")
        lines.append(file.content.rstrip())
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


def write_fix_bundle(repo_path: Path, report: ProofReport, output_dir: Path, apply: bool = False) -> tuple[FixBundle, list[GeneratedArtifact]]:
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_files = generate_fix_files(repo_path, report)
    artifacts: list[GeneratedArtifact] = []

    if not generated_files:
        summary_path = output_dir / "fix-summary.json"
        summary = FixBundle([], None, None, str(summary_path), applied=False, message="No safe automatic fix patch could be generated.")
        summary_path.write_text(json.dumps(asdict(summary), indent=2), encoding="utf-8")
        artifacts.append(GeneratedArtifact("Fix Summary", str(summary_path), "Auto-fix generation result"))
        return summary, artifacts

    patch_path = output_dir / "fix.patch"
    tests_md_path = output_dir / "generated-tests.md"
    summary_path = output_dir / "fix-summary.json"

    patch_path.write_text(render_unified_patch(generated_files), encoding="utf-8")
    tests_md_path.write_text(render_generated_tests_markdown(report, generated_files), encoding="utf-8")

    applied = False
    if apply:
        for generated in generated_files:
            target = repo_path / generated.path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(generated.content, encoding="utf-8")
        applied = True

    bundle = FixBundle(
        generated_files=generated_files,
        patch_path=str(patch_path),
        generated_tests_path=str(tests_md_path),
        summary_path=str(summary_path),
        applied=applied,
        message="Generated additive proof-hardening tests." + (" Applied to repository." if applied else " Patch not applied."),
    )
    summary_path.write_text(json.dumps(asdict(bundle), indent=2), encoding="utf-8")

    artifacts.extend([
        GeneratedArtifact("Fix Patch", str(patch_path), "Unified diff containing generated proof-hardening tests"),
        GeneratedArtifact("Generated Tests", str(tests_md_path), "Human-readable explanation of generated tests"),
        GeneratedArtifact("Fix Summary", str(summary_path), "Machine-readable auto-fix generation result"),
    ])
    return bundle, artifacts
