from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path

from .models import GeneratedArtifact, ProofReport


@dataclass
class GitPrPack:
    branch_name: str
    commit_message: str
    title: str
    body_path: str
    commands_path: str
    summary_path: str
    created_branch: bool = False
    committed: bool = False
    message: str = ""


def _run_git(args: list[str], cwd: Path) -> tuple[int, str, str]:
    completed = subprocess.run(["git", *args], cwd=str(cwd), text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return completed.returncode, completed.stdout.strip(), completed.stderr.strip()


def _safe_branch(project: str) -> str:
    cleaned = "".join(ch.lower() if ch.isalnum() else "-" for ch in project).strip("-") or "project"
    return f"basalt/proof-hardening-{cleaned}"


def render_pr_body(report: ProofReport, include_fix: bool = True) -> str:
    lines = [
        "# Basalt Proof Hardening",
        "",
        f"Project: `{report.project_name}`",
        f"Basalt verdict: `{report.final_status.value}`",
        f"Proof score: `{report.score}/100`",
        "",
        "## What Basalt checked",
        "",
        "- Build / lint / typecheck / test commands from `basalt.yaml` or project inference",
        "- Security, secret, auth-risk, destructive migration, and dependency hygiene signals",
        "- Mutation testing to detect weak tests",
        "- AST-Anchored Project Graph preview",
        "- Policy Kernel blocking rules",
        "",
        "## Required changes",
    ]
    if report.fix_suggestions:
        for s in report.fix_suggestions:
            files = f" Affected: {', '.join(s.affected_files)}." if s.affected_files else ""
            lines.append(f"- **[{s.severity}] {s.title}:** {s.problem}{files}")
    else:
        lines.append("- No remediation required. Basalt marked the repository verified.")
    lines += [
        "",
        "## Basalt acceptance checklist",
        "",
        "- [ ] `basalt verify .` returns `VERIFIED` or remaining risk has explicit human approval",
        "- [ ] No blocking policy findings remain",
        "- [ ] Survived mutations are killed by tests or documented as accepted risk",
        "- [ ] Proof Report and dashboard artifacts are attached or linked",
        "",
        "## Generated evidence",
        "",
    ]
    for artifact in report.artifacts:
        lines.append(f"- **{artifact.name}:** `{artifact.path}` — {artifact.purpose}")
    lines.append("")
    if include_fix:
        lines.append("This PR body was generated by Basalt MVP v1.5. Review before merging.")
    return "\n".join(lines) + "\n"


def render_git_commands(pack: GitPrPack, remote: str | None = None) -> str:
    lines = [
        "# Basalt GitHub PR Commands",
        "",
        "Run these from the repository root after reviewing the generated patch:",
        "",
        "```bash",
        f"git checkout -b {pack.branch_name}",
        "git add .",
        f"git commit -m {json.dumps(pack.commit_message)}",
    ]
    if remote:
        lines.append(f"git push -u {remote} {pack.branch_name}")
        lines.append("# Then open a pull request using github-pr-description.md as the PR body.")
    else:
        lines.append("# git push -u origin " + pack.branch_name)
        lines.append("# Then open a pull request using github-pr-description.md as the PR body.")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def write_pr_pack(repo_path: Path, report: ProofReport, output_dir: Path, branch: str | None = None, create_branch: bool = False, commit: bool = False, remote: str | None = None) -> tuple[GitPrPack, list[GeneratedArtifact]]:
    output_dir.mkdir(parents=True, exist_ok=True)
    branch_name = branch or _safe_branch(report.project_name)
    title = f"Basalt proof hardening for {report.project_name}"
    commit_message = "Basalt proof hardening"
    body_path = output_dir / "github-pr-description.md"
    commands_path = output_dir / "github-pr-commands.md"
    summary_path = output_dir / "github-pr-pack.json"

    body_path.write_text(render_pr_body(report), encoding="utf-8")
    pack = GitPrPack(
        branch_name=branch_name,
        commit_message=commit_message,
        title=title,
        body_path=str(body_path),
        commands_path=str(commands_path),
        summary_path=str(summary_path),
        message="Generated PR-ready pack. No git state changed.",
    )

    if create_branch or commit:
        if shutil.which("git") is None:
            pack.message = "Git was not found. Generated PR pack only."
        elif not (repo_path / ".git").exists():
            pack.message = "Repository is not a git repo. Generated PR pack only."
        else:
            code, _, err = _run_git(["checkout", "-B", branch_name], repo_path)
            if code == 0:
                pack.created_branch = True
                pack.message = f"Created or reset branch {branch_name}."
                if commit:
                    _run_git(["add", "."], repo_path)
                    code, _, err = _run_git(["commit", "-m", commit_message], repo_path)
                    if code == 0:
                        pack.committed = True
                        pack.message += " Created local commit."
                    else:
                        pack.message += f" Commit skipped/failed: {err or 'nothing to commit'}"
            else:
                pack.message = f"Could not create branch: {err}"

    commands_path.write_text(render_git_commands(pack, remote=remote), encoding="utf-8")
    summary_path.write_text(json.dumps(asdict(pack), indent=2), encoding="utf-8")
    return pack, [
        GeneratedArtifact("GitHub PR Description", str(body_path), "Copy/paste PR body with Basalt proof evidence"),
        GeneratedArtifact("GitHub PR Commands", str(commands_path), "Safe local Git commands for branch/commit/PR flow"),
        GeneratedArtifact("GitHub PR Pack JSON", str(summary_path), "Machine-readable PR automation metadata"),
    ]
